### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by thorwhalen** [scottmmjackson/get-the-default-branch-action#1]
Running this script, I get:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Might want to replace `action.yml` with:

```yaml
name: 'Get The Default Branch'
description: 'Get the default branch for this repository'
branding:
  icon: 'git-branch'
  color: 'green'
outputs:
  default_branch:
    description: "The default branch name"
runs:
  using: 'composite'
  steps:
    - id: default-branch-name
      shell: bash
      run: |
        default_branch=$(curl -s https://api.github.com/repos/${{ github.repository }} -H "Authorization: bearer ${{ github.token }}" | jq -r .default_branch)
        echo "default_branch=$default_branch" >> $GITHUB_OUTPUT
```
